package org.myframeworks.enums;

public enum ConfigProperties {
    URL,
    OVERRIDE_REPORTS,
    PASSED_EACH_STEPS_SCREENSHOTS,
    FAILED_EACH_STEPS_SCREENSHOTS,
    SKIPPED_EACH_STEPS_SCREENSHOTS,
    WAIT,
    RETRY,
    RETRY_FAILED_TESTS,
    RUN_MODE,
    SELENIUM_GRID_URL
}